# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# Required by RNFirebase

target 'jobsfee' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Firebase/Core', '~> 4.13.0'

  target 'jobsfeeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'jobsfee-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for jobsfee-tvOS

  target 'jobsfee-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
